// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class seleniumTesteFuncional {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:5000"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testefuncionalcomselenium() {
    driver.get("https://localhost:5000/");
    driver.manage().window().setSize(new Dimension(1456, 876));
    {
      WebElement element = driver.findElement(By.id("download-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".indicators")).click();
    driver.findElement(By.cssSelector(".indicator-item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".indicator-item:nth-child(2)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".indicator-item:nth-child(3)")).click();
    vars.put("win5233", waitForWindow(2000));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Universidad Rey Juan Carlos")).click();
    vars.put("win2727", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2727").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win2727").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win5233").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Angular")).click();
    vars.put("win8639", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8639").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win8639").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.id("logo-container")).click();
    {
      WebElement element = driver.findElement(By.id("download-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("signUpButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("signUpButton")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".modal-action")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > .navbar-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) > .navbar-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("jurema@gmail.com");
    {
      WebElement element = driver.findElement(By.id("log-in-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("44");
    driver.findElement(By.id("log-in-btn")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".material-icons")).click();
    driver.findElement(By.cssSelector(".modal-action")).click();
    driver.findElement(By.id("signUpButton")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lenora@gmail.com");
    driver.findElement(By.id("nickName")).click();
    driver.findElement(By.id("nickName")).sendKeys("lenora");
    driver.findElement(By.id("password")).sendKeys("784512");
    driver.findElement(By.id("confirmPassword")).click();
    driver.findElement(By.id("confirmPassword")).sendKeys("784512");
    driver.switchTo().frame(0);
    driver.findElement(By.id("recaptcha-anchor-label")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("sign-up-btn")).click();
    driver.findElement(By.cssSelector(".material-icons")).click();
    driver.findElement(By.id("nickName")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("784512Le");
    driver.findElement(By.id("confirmPassword")).click();
    {
      WebElement element = driver.findElement(By.id("sign-up-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("confirmPassword")).sendKeys("784512Le");
    driver.findElement(By.id("sign-up-btn")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".material-icons:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".material-icons:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".material-icons:nth-child(3)")).click();
    driver.findElement(By.id("arrow-drop-down")).click();
    driver.findElement(By.id("contact-button")).click();
    {
      WebElement element = driver.findElement(By.id("settings-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("settings-button")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".col:nth-child(5) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(4) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(1) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(2) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(3) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(3) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(3) .lever")).click();
    driver.findElement(By.cssSelector(".col:nth-child(3) .lever")).click();
    driver.findElement(By.cssSelector(".label-input-file")).click();
    {
      WebElement element = driver.findElement(By.id("logo-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".label-input-file")).click();
  }
}

